version: '3.8'

# This file defines the services that make up the AFM project environment.
# It uses a reverse proxy (nginx) to route traffic to the appropriate service.

services:
  # The reverse proxy is the single entry point for the user at http://localhost
  proxy:
    image: nginx:1.25-alpine
    container_name: afm_proxy
    volumes:
      # Mount our custom nginx configuration
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # Map port 8080 of the host to port 80 in the container
      - "8080:80"
    depends_on:
      - spec
      - try-it-app
    restart: unless-stopped

  # Service 1: The specification website (MkDocs with Material theme)
  spec:
    build: ./spec
    container_name: afm_spec
    command: mkdocs serve --dev-addr 0.0.0.0:8000
    volumes:
      # Mount the local spec directory into the container for live reloading
      # Any change to files in ./spec on your machine will trigger a rebuild.
      - ./spec:/app
    restart: unless-stopped
    # The proxy will forward traffic, so no port mapping is needed here.

  # Service 2: The "Try-it" SPA (currently a placeholder)
  try-it-app:
    build: ./try-it-app
    container_name: afm_try_it_app
    restart: unless-stopped
    # The proxy will forward traffic, so no port mapping is needed here.

volumes:
  # We can define named volumes here later for things like deployed agents
  deployed_apps:
